In [1]:
import numpy as np

def sor(A, b, x0=None, omega=1.25, tol=1e-8, max_iter=100):
    """
    Solves Ax = b using the Successive Over-Relaxation (SOR) method.

    Parameters
    ----------
    A : numpy.ndarray
        Coefficient matrix
    b : numpy.ndarray
        Right-hand side vector
    x0 : numpy.ndarray, optional
        Initial guess
    omega : float
        Relaxation parameter (0 < omega < 2)
        omega = 1 gives Gauss-Seidel
    tol : float
        Tolerance for stopping criterion
    max_iter : int
        Maximum number of iterations

    Returns
    -------
    x : numpy.ndarray
        Approximate solution
    iterations : int
        Number of iterations used
    history : list
        List of iterates for convergence tracking
    """
    n = len(b)

    if x0 is None:
        x = np.zeros(n, dtype=float)
    else:
        x = x0.astype(float)

    history = [x.copy()]

    for k in range(max_iter):
        x_old = x.copy()

        for i in range(n):
            # Sum using the newest available values
            sigma1 = np.dot(A[i, :i], x[:i])

            # Sum using the old values for the remaining entries
            sigma2 = np.dot(A[i, i+1:], x_old[i+1:])

            # SOR update formula
            x[i] = (1 - omega) * x_old[i] + (omega / A[i, i]) * (b[i] - sigma1 - sigma2)

        history.append(x.copy())

        # Stop if infinity norm of difference is small enough
        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            return x, k + 1, history

    return x, max_iter, history


# ---------------------------------------------------
# Example 1
# ---------------------------------------------------
# A diagonally dominant system

A1 = np.array([
    [4, 1, 2],
    [3, 5, 1],
    [1, 1, 3]
], dtype=float)

b1 = np.array([4, 7, 3], dtype=float)

x1, iter1, hist1 = sor(A1, b1, omega=1.1, tol=1e-10, max_iter=100)

print("=" * 60)
print("Example 1")
print("Matrix A:")
print(A1)
print("Vector b:")
print(b1)
print("Approximate solution by SOR:")
print(x1)
print("Number of iterations:", iter1)

# Compare with exact solution from NumPy
x1_exact = np.linalg.solve(A1, b1)
print("Exact solution:")
print(x1_exact)
print("Infinity norm of error:", np.linalg.norm(x1 - x1_exact, ord=np.inf))


# ---------------------------------------------------
# Example 2
# ---------------------------------------------------
# Another linear system

A2 = np.array([
    [10, -1, 2, 0],
    [-1, 11, -1, 3],
    [2, -1, 10, -1],
    [0, 3, -1, 8]
], dtype=float)

b2 = np.array([6, 25, -11, 15], dtype=float)

x2, iter2, hist2 = sor(A2, b2, omega=1.2, tol=1e-10, max_iter=200)

print("=" * 60)
print("Example 2")
print("Matrix A:")
print(A2)
print("Vector b:")
print(b2)
print("Approximate solution by SOR:")
print(x2)
print("Number of iterations:", iter2)

# Compare with exact solution from NumPy
x2_exact = np.linalg.solve(A2, b2)
print("Exact solution:")
print(x2_exact)
print("Infinity norm of error:", np.linalg.norm(x2 - x2_exact, ord=np.inf))
print("=" * 60)

Example 1
Matrix A:
[[4. 1. 2.]
 [3. 5. 1.]
 [1. 1. 3.]]
Vector b:
[4. 7. 3.]
Approximate solution by SOR:
[0.5 1.  0.5]
Number of iterations: 13
Exact solution:
[0.5 1.  0.5]
Infinity norm of error: 3.4406921756158226e-12
Example 2
Matrix A:
[[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]
Vector b:
[  6.  25. -11.  15.]
Approximate solution by SOR:
[ 1.  2. -1.  1.]
Number of iterations: 18
Exact solution:
[ 1.  2. -1.  1.]
Infinity norm of error: 6.2303495695914535e-12
